"""
Django settings for tnnt project.

Generated by 'django-admin startproject' using Django 3.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path
from datetime import datetime, timezone

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
XLOG_DIR = os.path.join(BASE_DIR, 'xlog')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
import os
SECRET_KEY = os.environ['SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'

# ALLOWED_HOSTS = []
# Include localhost for IRC bot API access
ALLOWED_HOSTS = ['tnnt.org', 'www.tnnt.org', 'localhost', '127.0.0.1']
if DEBUG:
    # Required for debug context variable in templates
    INTERNAL_IPS = ['127.0.0.1', 'localhost']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',  # CORS support for API
    'rest_framework',
    'scoreboard.apps.ScoreboardConfig',
    'tnnt',
]
if not DEBUG:
    # When DEBUG = True, Django serves local static files.
    # In prod, we use whitenoise to serve the files. runserver_nostatic must
    # come BEFORE django.contrib.staticfiles to override its runserver.
    INSTALLED_APPS.insert(0, 'whitenoise.runserver_nostatic')

REST_FRAMEWORK = {
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 100,
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS must be before CommonMiddleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'tnnt.middleware.LoginControlMiddleware',  # Must be after AuthenticationMiddleware
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
if not DEBUG:
    MIDDLEWARE.append('whitenoise.middleware.WhiteNoiseMiddleware')

# Required when using Django version 4.x
# CSRF_TRUSTED_ORIGINS = []
CSRF_TRUSTED_ORIGINS = ['https://tnnt.org', 'https://www.tnnt.org']

# Secure cookie settings for HTTPS in production
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_SAMESITE = 'Lax'
    SESSION_COOKIE_SAMESITE = 'Lax'

ROOT_URLCONF = 'tnnt.urls'

SETTINGS_PATH = os.path.dirname(__file__)

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(SETTINGS_PATH, 'templates'),
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'tnnt.context_processors.admin_status',
            ],
        },
    },
]

WSGI_APPLICATION = 'tnnt.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'scoreboard',
        'USER': 'tnnt',
        'PASSWORD': os.environ['DATABASE_PASSWORD'],
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATIC_URL = 'static/'

if not DEBUG:
    # Django 5.1 removed STATICFILES_STORAGE; storage backends are configured
    # through STORAGES, which must also carry the 'default' entry.
    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
        },
    }

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Session expiration. The cookie is dropped when the browser closes; the
# server-side session still expires after SESSION_COOKIE_AGE regardless.

SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 7 * 24 * 60 * 60 # in seconds, so 1 week

# Where you get taken after logging in/out

LOGIN_REDIRECT_URL = '/clanmgmt'
LOGOUT_REDIRECT_URL = '/'

# Custom authentication backend (hooks into dgamelaunch)

AUTHENTICATION_BACKENDS = [
    'tnnt.hardfought_utils.HdfAuthBackend',
]

# Path to dgl sqlite3 database

DGL_DATABASE_PATH = '/opt/nethack/chroot/dgldir/dgamelaunch.db'
if DEBUG:
    DGL_DATABASE_PATH = './dgamelaunch_test.db'

# Path to where TNNT is writing temp achievement files
# If you don't want to show temp achievements, leave this uncommented
TEMP_ACHIEVEMENTS_PATH = '/opt/nethack/chroot/tnnt/temp_achievements'

# Clan size limit

MAX_CLAN_PLAYERS = 12

# Clan freeze (no new clan creation / joining clans)
# Can be disabled by setting CLAN_FREEZE_TIME environment variable to empty string
clan_freeze_env = os.environ.get('CLAN_FREEZE_TIME', '2026-11-10T00:00:00+00:00')
CLAN_FREEZE_TIME = datetime.fromisoformat(clan_freeze_env) if clan_freeze_env else None

# Site administrators (player names from dgamelaunch database)
# These users can access the admin panel and control site settings
SITE_ADMINS = ['k2', 'aosdict', 'aoei']

# Tournament start/end times

TOURNAMENT_START = datetime.fromisoformat('2026-11-01T00:00:00+00:00')
TOURNAMENT_END   = datetime.fromisoformat('2026-12-01T00:00:00+00:00')

# Main log file
# Use absolute path for production. Relative paths (e.g., "tnnt.log")
# will create the log file in the project root directory
TNNT_LOG_FILE = "/var/log/tnnt/tnnt_server.log"

# Django logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'normal': {
            'format': '%(levelname)s %(asctime)s %(message)s',
            'style': '%', # use {} to enclose variables in logging calls
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG' if DEBUG else 'INFO',
            'class': 'logging.FileHandler',
            'filename': TNNT_LOG_FILE,
            'formatter': 'normal',
        },
        'console': {
            'class': 'logging.StreamHandler',
            'level': 'DEBUG',
            'formatter': 'normal'
        },
    },
    'root': {
        'handlers': [ 'file', 'console' ],
        'level': 'DEBUG',
    },
    'loggers': {
        'passlib': {
            'handlers': ['file', 'console'],
            'level': 'WARNING',  # Suppress passlib DEBUG messages
            'propagate': False,
        },
    },
}

# URLs of swapchest donor files, which will get downloaded and parsed during
# aggregation.
DONOR_FILES = [
    'https://www.hardfought.org/xlogfiles/tnnt/donors',
    'https://eu.hardfought.org/xlogfiles/tnnt/donors',
    'https://au.hardfought.org/xlogfiles/tnnt/donors'
]

# CORS Configuration for API access
# Configure allowed origins for production
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # Local development
    "http://127.0.0.1:3000",  # Local development
    "http://localhost:8000",  # Local Django dev server
    "http://127.0.0.1:8000",  # Local Django dev server
    # Production URLs:
    "https://tnnt.org",
    "https://www.tnnt.org",
    # Note: IRC bot runs on same server, uses localhost:8000 directly
    # No CORS needed for server-side bot requests
]

# For development, you can use this instead (but never in production):
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True  # Allow all origins in DEBUG mode
else:
    CORS_ALLOW_ALL_ORIGINS = False  # Use whitelist in production

# Allow credentials to be included in CORS requests
CORS_ALLOW_CREDENTIALS = True

# Specify which headers can be used during the actual request
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Regexes for unique deaths handling.
# Normalizations are a list of 2-tuples of regex and string, which will be the
# first and second arguments to a re.sub() call whose third argument is the
# death string. They are executed in the order they appear here.
# Rejections are a flat list of regexes that, should they match a death (after
# it's been normalized), will remove it from consideration.
UNIQUE_DEATH_REJECTIONS = [
    r"^ascended",
    r"^quit",
    r"^escaped",
]
UNIQUE_DEATH_NORMALIZATIONS = [
    (r"^killed by an ", "killed by a "),
    (r", while .*", ""),
    (r"hallucinogen-distorted ", ""),
    (r"by the invisible ", "by the "),
    # this turns "invisible stalker" into just "stalker" but that's fine since
    # there's no other way to get killed by some other stalker
    (r"by (an|a) invisible ", "by a "),
    (r"by invisible ", "by "),
    (r"by .*; the shopkeeper", "by a shopkeeper"),
    (r" (her|his) ", " their "),
    (r" (herself|himself) ", " themselves "),
    (r" (herself|himself)$", " themselves"),
    (r" (called|named) .*", ""),
    (r"choked on .*", "choked on something"),
    (r"killed by kicking .*", "killed by kicking something"),
    (r"killed by touching .*", "killed by touching an artifact"),
    # (r"killed by a falling (?!rock)$", "killed by a falling object"), # don't think we need this
    (r" (an? )?M[rs]\. [A-Z].*[,;] the shopkeeper", " a shopkeeper"),
    (r"poisoned by a rotted .* corpse", "poisoned by a rotted corpse"),
    (r"poisoned by a rotted glob .+", "poisoned by a rotted glob"),
    (r"wrath of .+", "wrath of a deity"),
    (r"priest(ess)?", "priest(ess)"),
    # This next one must come after the last one, because it assumes the
    # priest/priestess has already turned into already priest(ess) with the
    # parens
    (r"priest\(ess\) of .+", "priest(ess) of a deity"),
    # this is ugly... it's the list of things that can be summoned as a minion
    # (to prevent farming a bunch of unique deaths off repeated prayers until
    # the god summons a minion)
    (r"an? (\w+ elemental|Aleax|couatl|Angel|\w+ demon|\w+ devil|(suc|in)cubus|balrog|pit fiend|nalfeshnee|hezrou|vrock|marilith|erinyes) of .+", "a minion of a deity"),
    # "chameleon imitating a monster" is its own unique death, rather than
    # treating it as the monster it was imitating, but all monsters turn into
    # just "monster"; however, "killed by a chameleon" when it's not imitating
    # anything will not be normalized, because getting killed by it when it's in
    # its natural form actually is a distinct unique death
    (r"(chameleon|sandestin|doppelganger) imitating an? .+", r"\1 imitating a monster"),
    # deaths to player remnant monsters in bones should count the same as the
    # basic monster type
    (r"[^ ]+'s ghost", "a ghost"),
    (r"[^ ]+ the (vampire|ghoul|wraith|green slime)", r"a \1"),
    (r"[^ ]+ the (gnome|orc|dwarf|elf|human) mummy", r"a \1 mummy"),
    # TNNT TODO FOR 3.7: add "zombie" to the above case with a second
    # backreference, as it is now possible to arise as those
    # TNNT TODO FOR 3.7: deaths to remnant monsters have some differences in
    # formatting. It appears to now be "killed by the [remnant monster] of
    # [plname]" in all cases (ghosts and non-ghosts).
    # TNNT TODO FOR 3.7: there are complex death strings like the following:
    # "killed by the touch of death inflicted by a chameleon imitating an arch-lich"
    # Getting killed by a touch of death is notable, but can happen for a
    # variety of monsters even if we normalize away the shapechanger bit.
    # Various ways this could be handled:
    #  1. This counts towards only a generic "touch of death".
    #  2. This counts towards only "chameleon imitating a monster".
    #  3. Only the arch-lich part is normalized away; getting killed by a touch
    #     of death is significant and uncommon enough that different monster
    #     species inflicting it is OK to treat them as unique. (Note that there
    #     are other death strings, though, that are constructed like this but
    #     where the death is pretty mundane, like "arrow shot by a gnome lord").
    #  4. We implement some multiple unique deaths system and this counts for
    #     both "touch of death" and "chameleon imitating a monster".
]
'''
Deaths that are deliberately NOT normalized:
  - Vampires have several combinations:
    "vampire in fog cloud form"
    "vampire in bat form"
    "vampire lord in fog cloud form"
    "vampire lord in bat form"
    "vampire lord in wolf form"
    These aren't numerous enough or repeatable enough to get a wide variety of
    unique deaths, like can happen with chameleons.
    (Technically add 3 more vampire unique deaths for Vlad, but it would take
    quite a lot of effort to die to Vlad in a form other than his natural one
    and if anyone manages it, they deserve the unique death).
  - The "(with the Amulet)" suffix on deaths when the hero was carrying the
    Amulet is intentionally not normalized out. Getting a (likely) unique
    death is an intentional consolation prize.
  - Deaths from petrifying corpses do not normalize "chickatrice corpse" into
    "cockatrice corpse". Chickatrices are rarer and less likely to drop a
    corpse, so it's noticeably more difficult to set up unique deaths with them.
    If it turns out most of these deaths get accomplished by wishing for
    corpses, though, we may want to revisit it.
'''
